version: v{build}

os:
  - Visual Studio 2019 Preview

init:
  - git config --global core.autocrlf input
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

install:
  - git submodule update --init --recursive
  - vcpkg install catch2:x86-windows catch2:x64-windows

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -H. -BBuild -A%PLATFORM%

build:
  project: Build\TheRayTracerChallenge.sln
  parallel: true
  verbosity: normal

test_script:
  - cd Build
  - ctest -V -j 2 -C %CONFIGURATION%

cache: c:\tools\vcpkg\installed\
